export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const CHECKOUT_TICKET_INFO = 'CHECKOUT_TICKET_INFO'
export const GET_TICKET_INFO_SUCCESS = 'GET_TICKET_INFO_SUCCESS'
export const GET_TICKET_INFO_FAILURE = 'GET_TICKET_INFO_FAILURE'
export const GO_TO_NEXT_PLAN = 'GO_TO_NEXT_PLAN'

export const CHECKOUT_TICKET_RULES = 'CHECKOUT_TICKET_RULES'
export const GET_TICKET_RULES_SUCCESS = 'GET_TICKET_RULES_SUCCESS'
export const GET_TICKET_RULES_FAILURE = 'GET_TICKET_RULES_FAILURE'

// bettingChoice
export const SET_LEVEL = 'SET_LEVEL'
export const SET_PLAY = 'SET_PLAY'
export const SET_MULTIPLE = 'SET_MULTIPLE'
export const SET_UNIT = 'SET_UNIT'
export const SET_STATISTICS = 'SET_STATISTICS'
export const SET_PLAY_INFO = 'SET_PLAY_INFO'
export const SET_CHECKOUT_CHOICE = 'SET_CHECKOUT_CHOICE'
export const UPDATE_BONUS = 'UPDATE_BONUS'
