export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const CHECKOUT_TICKET_INFO = 'CHECKOUT_TICKET_INFO'
export const GET_TICKET_INFO_SUCCESS = 'GET_TICKET_INFO_SUCCESS'
export const GET_TICKET_INFO_FAILURE = 'GET_TICKET_INFO_FAILURE'
