

const quickPay = [
  {
    type: 9,
    name: 'quickpay',
    zhName: '快捷支付',
    className: 'fc-re-quickpay',
    pic: require('./quickpay.png'),
    sortId: 4,
    risky: true,
  },
  {
    type: 1,
    name: 'unionpay',
    zhName: '银联支付一',
    className: 'fc-re-union',
    pic: require('./union.png'),
    sortId: 1,
    risky: false,
  },
  {
    type: 4,
    name: 'unionpay2',
    zhName: '银联支付二',
    className: 'fc-re-union',
    pic: require('./union.png'),
    sortId: 2,
    risky: false,
  },
  {
    type: 5,
    name: 'unionpay3',
    zhName: '银联支付三',
    className: 'fc-re-union',
    pic: require('./union.png'),
    sortId: 3,
    risky: false,
  },
  {
    type: 3,
    name: 'wechat',
    zhName: '微信支付一',
    className: 'fc-re-wechat',
    pic: require('./wechat.png'),
    sortId: 8,
    risky: true,
  },
  {
    type: 7,
    name: 'wechat',
    zhName: '微信支付二',
    className: 'fc-re-wechat',
    pic: require('./wechat.png'),
    sortId: 9,
    risky: true,
  },
  {
    type: 10,
    name: 'wechat',
    zhName: '微信支付三',
    className: 'fc-re-wechat',
    pic: require('./wechat.png'),
    sortId: 10,
    risky: true,
  },
  {
    type: 2,
    name: 'alipay',
    zhName: '支付宝支付',
    className: 'fc-re-alipay',
    pic: require('./alipay.png'),
    sortId: 11,
    risky: true,
  },
  {
    type: 6,
    name: 'alipay',
    zhName: '支付宝转账',
    className: 'fc-re-alipay',
    pic: require('./alipay.png'),
    sortId: 6,
    risky: true,
  },
  {
    type: 8,
    name: 'creditpay',
    zhName: '信用卡支付',
    className: 'fc-re-union',
    pic: require('./union.png'),
    sortId: 12,
    risky: false,
  },
  {
    type: 11,
    name: 'banktransfer',
    zhName: '银行卡转账',
    className: 'fc-re-banktransfer',
    pic: require('./union.png'),
    sortId: 5,
    risky: true,
  },
  {
    type: 12,
    name: 'scancode',
    zhName: '扫码支付',
    className: 'fc-re-scancode',
    pic: require('./union.png'),
    sortId: 7,
    risky: true,
  },
  {
    type: 13,
    name: 'QQ',
    zhName: 'QQ扫码支付',
    className: 'fc-re-qqscancode',
    pic: require('./union.png'),
    sortId: 13,
    risky: true,
  },
  {
    type: 14,
    name: 'unionscancode',
    zhName: '银联扫码支付',
    className: 'fc-re-scancode',
    pic: require('./union.png'),
    sortId: 14,
    risky: true,
  },
]

module.exports = {
  get(id) {
    return _(quickPay).findWhere({
      type: id,
    })
  },
}
